---
title: "compare_dm"
author: "caitlinpage"
date: "2024-09-04"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

## Introduction


```{r}
library(Damsel)
library(plyranges)
library(dplyr)
library(tidyr)
library(ggplot2)

library(BSgenome.Dmelanogaster.UCSC.dm6)
library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)
library(org.Dm.eg.db)
library(ggVennDiagram)
```

```{r}
gatc_regions <- getGatcRegions(BSgenome.Dmelanogaster.UCSC.dm6::BSgenome.Dmelanogaster.UCSC.dm6)$regions %>% data.frame()
```

# Compare DM results

```{r}
damsel_dm <- readRDS("../output/damsel_dm.rds")
vissers_dm <- readRDS("../output/vissers_dm.rds")
```
```{r}
head(damsel_dm)
head(vissers_dm)
```
```{r}
dm_compare <- damsel_dm %>%
  mutate(vissers_logFC = vissers_dm[match(damsel_dm$Position, row.names(vissers_dm)), "logFC"]) %>%
  mutate(vissers_PValue = vissers_dm[match(.$Position, row.names(vissers_dm)), "PValue"]) %>%
  mutate(vissers_dm = vissers_dm[match(damsel_dm$Position, row.names(vissers_dm)), "significant"],
         vissers_logFC = ifelse(is.na(vissers_logFC), 0, vissers_logFC),
         vissers_PValue = ifelse(is.na(vissers_PValue), 1, vissers_PValue))
head(dm_compare)
```

## compare P Values
```{r}
dm_compare %>%
  ggplot(aes(x = vissers_PValue, y = PValue)) +
  geom_point(alpha = 0.1) +
  geom_vline(xintercept = 0.05, colour = "red", linetype = "dashed") +
  geom_hline(yintercept = 0.05, colour = "red", linetype = "dashed") +
  geom_smooth() +
  labs(y = "Damsel PValue", x = "Vissers PValue")
```


```{r}
cor.test(dm_compare$vissers_PValue, dm_compare$PValue)
```

